#!/usr/bin/env php
<?php

global $argv;

require __DIR__ . "/vendor/autoload.php";

use Dhruv125\Coretex\ConsoleHelper;
use Dhruv125\Coretex\Templater\Template;

$printer = new ConsoleHelper();

function help() {
	global $printer;
	$printer->print("Usage: ", 'red', '', true, false);
	$printer->print("php ", 'green', '', true, false);
	$printer->print('worker ', 'cyan', '', true, false);
	$printer->print("[OPTION]...", 'green', '', true, true);
	$printer->print("Executing Commands for easy components management - OwnWork\n", 'green', '', false);
	$printer->print("OPTIONS:\n", 'red', '', true);
	$printer->print("make", 'green', '', true, false);
	echo " - Making Components, it's arguments:\n";
	$printer->print("    > controller - Make Controller File", 'green', '', true);
	$printer->print("    > model - Make Model File", 'green', '', true);
	$printer->print("    > view - Make View File", 'green', '', true);
	$printer->print("\nserve", 'green', '', true, false);
	echo " - Serve OwnWork Application, it's optional arguments:\n";
	$printer->print("    > NUMBER - Provide a Port Number else, Server Will Start at default port: 8000", 'green', '', true);
	$printer->print("\ntranspile", 'green', '', true, false);
	echo " - Run the Temp View transpiler:\n";
	echo " - Transpiled views will be stored in 'storage/views/' directory.\n";
	echo " - View method will pick mapping for temp views from 'storage/views.json'.\n";
	$printer->print("It's Optional Arguments are:\n", 'blue', '', true, false);
	$printer->print("    > NUMBER - Provide number of times transpiler should run and then terminate [Used for production build]", 'green', '', true);
	$printer->print("    > build - Clear View cache and build for production", 'green', '', true);
	$printer->print("\nclear:viewcache", 'green', '', true, false);
	echo " - Clear View Cache Stored in 'storage/views/' directory:\n";
}

// print_r($argv);
// echo "\n";
$dirArray = [
	'controller' => __DIR__ . "/app/Controller/",
	'view' => __DIR__ . "/resources/views/",
	'model' => __DIR__ . "/app/Model/"
];

$baseDirArray = [
	'controller' => "app/Controller/",
	'view' => "resources/views/",
	'model' => "app/Model/"
];

$baseFileArray = [
	'controller' => __DIR__ . "/resources/template/Controller.php",
	'view' => __DIR__ . "/resources/template/View.php",
	'model' => __DIR__ . "/resources/template/Model.php"
];

$array_list = [$dirArray, $baseDirArray, $baseFileArray];

$firstArg = (isset($argv[1])) ? $argv[1] : false;
$validFirstArg = false;

foreach ($dirArray as $key => $value) {
	if (!is_dir($value)) {
		mkdir($value, 0664);
	}
}

if ($firstArg && $firstArg == "make") {
	$validFirstArg = true;
	if (isset($argv[2])) {
		$dirName = strtolower($argv[2]);
		switch ($dirName) {
		case 'controller':
			compCreate($array_list, $dirName);
			break;
		case 'model':
			compCreate($array_list, $dirName);
			break;
		case 'view':
			compCreate($array_list, $dirName);
			break;
		default:
			$printer->print("No Such Component Exists!\n", 'red', '', true);
			help();
			break;
		}
	} else {
		$printer->print("Provide Name of Component to make!\n", 'red', '', true);
		help();
	}
} else {
	//
}

if ($firstArg && strtolower($firstArg) == "serve") {
	$validFirstArg = true;
	$port = 8000;
	if (isset($argv[2]) && is_numeric($argv[2])) {
		$port = $argv[2];
	}
	$printer->print("Starting OwnWork server at port:$port...", "blue", true, true);
	$execServer = shell_exec("php --server=localhost:$port --docroot=public");
	$printer->print("Shutting Server", "red", true, true);
}

if ($firstArg && strtolower($firstArg) == "transpile") {
	$beginTime = microtime(true);
	$count = -1;
	$validFirstArg = true;
	$runAndEnd = false;
	if (isset($argv[2]) && strtolower($argv[2]) == "build") {
		$runAndEnd = true;
	}

	if (isset($argv[2]) && is_int(filter_var($argv[2], FILTER_VALIDATE_INT))) {
		$arg_int = (int) $argv[2];
		if ($arg_int > 0) {
			$count = $arg_int;
		}
	}
	$parser = new Template();

	if ($runAndEnd) {
		$parser->scanStorage();
		$parser->scanRes();
		$parser->compileFiles();
		$viewJson = json_encode($parser->giveCompiledViewArr());
		file_put_contents(approot() . "/storage/views.json", $viewJson);
		$endTime = microtime(true);
		$processTime = round($endTime - $beginTime, 5);
		$printer->print("Transpiled Template Views Files in ", 'blue', '', false, false);
		$printer->print("$processTime", 'blue', '', true, false);
		$printer->print(" seconds", 'blue', '', false);
		exit(0);
	}

	$printer->print("Waiting For View Files to Change!", "green", true, true);
	$i = -1;

	while (true) {
		sleep(1);

		$parser->scanStorage();
		$viewJson = json_encode($parser->giveCompiledViewArr());

		if ($i === -1) {
			$parser->scanRes();
			$viewJson = json_encode($parser->giveCompiledViewArr());
			file_put_contents(approot() . "/storage/views.json", $viewJson);
			$i++;
		}

		if ($parser->scanStorage()) {
			$i++;
			$printer->print("Files Changed! Retranspiling Views x$i", 'blue', '', true);
			$parser->clearViewCache();
			file_put_contents(approot() . "/storage/views.json", $viewJson);
			$parser->compileFiles();
			$printer->print("Done!", 'red', '', true);
		}

		if ($count === $i) {
			$printer->print("\nStopping Transpilation after $count operation!", 'red', '', true);
			exit();
		}
	}
}

if ($firstArg && strtolower($firstArg) == "clear:viewcache") {
	$validFirstArg = true;
	$dirPath = approot() . "/storage/views/";
	if (is_dir($dirPath)) {
		$dirList = scandir($dirPath);
		foreach($dirList as $currDir) {
			if ($currDir === '.' || $currDir === "..") continue;
			$filePath = $dirPath . $currDir;
			if (is_file($filePath)) {
				unlink($filePath);
			}
		}
		$printer->print("Successfully Cleared Template View Cache", 'green', '', true);
	}
}

function compCreate($arrList, $component, $compName = null) {
	global $argv;
	global $printer;
	$compName = (isset($argv[3])) ? $argv[3] : trim(readline("Enter " . $component ." name: "));
	if (!file_exists($arrList[0][$component] . $compName . ".php")) {
		touch($arrList[0][$component] . $compName . ".php");
		$templateContent = str_replace('DEFAULT_NAME', $compName, file_get_contents($arrList[2][$component]));
		file_put_contents($arrList[0][$component]. $compName . ".php", $templateContent);
		$printer->print("\n" . ucfirst($component) . " with name `", 'blue', '', true, false);
		$printer->print($compName, 'green', '', true, false);
		$printer->print("` created at:\n", 'blue', '', true, false);
		$printer->print("-> ", 'yellow', '', true, false);
		$printer->print($arrList[1][$component] . $compName . ".php\n", 'blue', '', true, false);
	} else {
		$printer->print("Component with name ", 'blue', '', true, false);
		$printer->print($compName, 'red', '', true, false);
		$printer->print(" Already exists at:\n", 'blue', '', true);
		// echo "-> ";
		$printer->print("-> ", 'yellow', '', true, false);
		$printer->print($arrList[1][$component] . $compName . ".php", 'red', '', true);
	}
}

if (!$firstArg) {
	help();
}

if ($firstArg && !$validFirstArg) {
	$printer->print("No Registered Command as \"$argv[1]\"!\n", 'red', '', true);
	help();
}
